<?php
/* please edit for yourself */
$smtp_host = "smtp.qq.com";
$smtp_port = 25;
$smtp_timeout = 3;
$smtp_charset = "utf-8";
$smtp_delimiter = "\n";

$smtp_user = "";
$smtp_pass = "";

$smtp_from = "";
$smtp_from_name = "";

$smtp_to = "";
$smtp_to_name = "";

$smtp_cc = "";
$smtp_cc_name = "";

$smtp_bcc = "";
$smtp_bcc_name = "";

$smtp_attachment = dirname(__FILE__)."/test.txt";
$smtp_attachment_name = "text";

$smtp_subject = "test";
$smtp_body = "just a test email";
